name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v4

        with:
          python-version: '3.12'
      - name: Install Requirements
        run:
          pip install -r requirements.txt
      - name: Pylint, Format & Types
        run:
           pylint src/ && black --check ./ && mypy src/ --strict
      - name: Tests
        run:
          python -m pytest tests
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          PROPOSER_PK: ${{ secrets.PROPOSER_PK }}
